/**
 * Royal Clouds icon registry — Lucide glyphs for every icon name the system
 * uses: the shared Astryx UI set (close, chevronDown, …) plus our semantic
 * content names (server, bolt, …). Sized at 1em so Astryx's Icon size tokens
 * drive the rendered size. Self-contained: the neutral theme's registry is not
 * an exported subpath, so the shared defaults are mapped here directly.
 */
import React from 'react';
import type {IconRegistry} from '@astryxdesign/core/Icon';
import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowLeftRight,
  ArrowUp,
  ArrowUpDown,
  BadgeDollarSign,
  Bolt,
  Calendar,
  Check,
  CheckCheck,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Clock,
  Cloud,
  Columns,
  Copy,
  Cpu,
  Database,
  DatabaseBackup,
  ExternalLink,
  EyeOff,
  FileText,
  Filter,
  Gauge,
  GitBranch,
  Globe,
  Headset,
  Info,
  LayoutDashboard,
  LayoutGrid,
  ListChecks,
  Lock,
  Mail,
  Menu,
  MessageSquare,
  Mic,
  MoreHorizontal,
  RefreshCw,
  Rocket,
  Search,
  Server,
  Settings,
  ShieldCheck,
  Square,
  Terminal,
  Users,
  Wallet,
  Wand2,
  BrickWall,
  Wrench,
  X,
  XCircle,
} from 'lucide-react';

const iconProps = {
  size: '1em',
  'aria-hidden': true as const,
};

/* Inferred first, then typed: IconRegistry is a Partial<Record<IconName, …>>
   and our content names (server, bolt, …) extend it. The intermediate binding
   keeps TS's excess-property check from firing on the literal. */
const registry = {
  // ── Shared Astryx UI set (same glyphs the neutral theme ships) ──────────
  close: <X {...iconProps} />,
  chevronDown: <ChevronDown {...iconProps} />,
  chevronLeft: <ChevronLeft {...iconProps} />,
  chevronRight: <ChevronRight {...iconProps} />,
  chevronsLeft: <ChevronsLeft {...iconProps} />,
  chevronsRight: <ChevronsRight {...iconProps} />,
  check: <Check {...iconProps} />,
  success: <CheckCircle {...iconProps} />,
  error: <XCircle {...iconProps} />,
  warning: <AlertTriangle {...iconProps} />,
  info: <Info {...iconProps} />,
  calendar: <Calendar {...iconProps} />,
  clock: <Clock {...iconProps} />,
  externalLink: <ExternalLink {...iconProps} />,
  menu: <Menu {...iconProps} />,
  moreHorizontal: <MoreHorizontal {...iconProps} />,
  search: <Search {...iconProps} />,
  arrowUp: <ArrowUp {...iconProps} />,
  arrowDown: <ArrowDown {...iconProps} />,
  arrowsUpDown: <ArrowUpDown {...iconProps} />,
  funnel: <Filter {...iconProps} />,
  eyeSlash: <EyeOff {...iconProps} />,
  viewColumns: <Columns {...iconProps} />,
  copy: <Copy {...iconProps} />,
  checkDouble: <CheckCheck {...iconProps} />,
  wrench: <Wrench {...iconProps} />,
  stop: <Square {...iconProps} />,
  microphone: <Mic {...iconProps} />,

  // ── Royal Clouds content set ────────────────────────────────────────────
  server: <Server {...iconProps} />,
  cpu: <Cpu {...iconProps} />,
  database: <Database {...iconProps} />,
  cloud: <Cloud {...iconProps} />,
  wordpress: <Globe {...iconProps} />,
  users: <Users {...iconProps} />,
  bolt: <Bolt {...iconProps} />,
  shield: <ShieldCheck {...iconProps} />,
  apps: <LayoutGrid {...iconProps} />,
  headset: <Headset {...iconProps} />,
  terminal: <Terminal {...iconProps} />,
  settings: <Settings {...iconProps} />,
  refresh: <RefreshCw {...iconProps} />,
  backup: <DatabaseBackup {...iconProps} />,
  scale: <Wand2 {...iconProps} />,
  billing: <BadgeDollarSign {...iconProps} />,
  rocket: <Rocket {...iconProps} />,
  failover: <GitBranch {...iconProps} />,
  uptime: <Activity {...iconProps} />,
  gauge: <Gauge {...iconProps} />,
  report: <FileText {...iconProps} />,
  audit: <ShieldCheck {...iconProps} />,
  logs: <ListChecks {...iconProps} />,
  firewall: <BrickWall {...iconProps} />,
  globe: <Globe {...iconProps} />,
  lock: <Lock {...iconProps} />,
  activity: <Activity {...iconProps} />,
  wallet: <Wallet {...iconProps} />,
  mail: <Mail {...iconProps} />,
  chat: <MessageSquare {...iconProps} />,
  dashboard: <LayoutDashboard {...iconProps} />,
  migrate: <ArrowLeftRight {...iconProps} />,
};

export const royalIconRegistry: IconRegistry = registry;
