/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/royal.theme.ts
 * Command: astryx theme build theme/royal.theme.ts --out app/royal-theme.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

/// <reference path="./royal.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const royalIconRegistry: IconRegistry;
export declare const royalTheme: DefinedTheme;
